### ISSUE TITLE
ZIPCODE_CONNECTION_STRING not set

### ISSUE THREAD

**Issue by bdl108** [ChrisMuir/Zillow#17]
Installed zipcode package, and getting following error when attempting to run:

`Exception: ZIPCODE_CONNECTION_STRING not set, 
http://docs.sqlalchemy.org/en/latest/core/engines.html#sqlalchemy.create_engine`

Python knowledge too limited to tell me what's going wrong here, and looking at the link didn't provide me any insights. Help?

**Comment by ChrisMuir** [comment]
This is an issue with the Python module [zipcode](https://github.com/buckmaxwell/zipcode), see [this](https://github.com/buckmaxwell/zipcode/issues/16) issue from that repo, which describes how to fix the error.
