### ISSUE TITLE
Could not find a version

### ISSUE THREAD

**Issue by cdbg2** [ChrisMuir/Zillow#3]
When trying to install zillow_functions I keep getting the message: Could not find a version that satisfies the requirement zillow_functions (from versions: )No matching distribution found for zillow_functions

! pip install zillow_functions

**Comment by wwetzel** [comment]
I am not sure what you mean by "install zillow_functions".  zillow_functions is the .py file that contains the functions zillow_runfile uses to scrape.  You don't install it but rather "run" it with your python framework.  You need python 3.x to run the file.  

You need to google "how to run a python file" for your specific platform.  You may also need to look into "venv" for creating a python 3x installation.

**Comment by cdbg2** [comment]
Thanks for the info. I was running it on python 2.7. Will upgrade to 3.6 and give it a shot.

**Comment by wwetzel** [comment]
Good luck with everything - this helped me a lot in figuring out how to have dual installations of python on my machine

http://python-guide-pt-br.readthedocs.io/en/latest/dev/virtualenvs/

**Comment by ChrisMuir** [comment]
Just now seeing this issue, thanks for jumping in @wwetzel.

And yeah, everything wwetzel mentioned is correct. This is not a module that can be pip installed, and Python 3 is required.
