### ISSUE TITLE
keyerror on pandas import

### ISSUE THREAD

**Issue by modelB** [ChrisMuir/Zillow#4]
I assume the error is mine rather than the code but when I step through I am getting a keyerror on import of pandas.  I am a novice programmer but spent several hours on stackoverflow and google looking for an answer with no luck.  Any help is appreciated.  

![image](https://user-images.githubusercontent.com/25725159/30839888-6ef4f966-a242-11e7-961f-5eb6124e69bc.png)

**Comment by ChrisMuir** [comment]
Hi @modelB , sorry you're running into issues.

To be honest, I've never seen a KeyError exception upon library import, but it indeed sounds like a local configuration issue (I'm NOT a Python expert though). Doing some quick googling, [this post](https://stackoverflow.com/questions/26737107/import-python-module-fails) and [this post](https://github.com/pandas-dev/pandas/issues/12084) are the closest things I could find to what you describe.

If worst comes to worst, I'm only using Pandas to house the output data frame, you could eliminate Pandas and use a different data structure to house the data (maybe a dictionary with the url strings as the keys).

**Comment by modelB** [comment]
Thanks, I am sure I'm doing something wrong.  Will figure it out.
