### ISSUE TITLE
add another final output variable: Saves

### ISSUE THREAD

**Issue by d0xish** [ChrisMuir/Zillow#6]
Would be convenient to scrape for how many saves a home has also!
![snippingtool_2017-11-30_22-00-09](https://user-images.githubusercontent.com/34150781/33468545-72f2109c-d61a-11e7-9962-71f0c60cf971.png)

**Comment by ChrisMuir** [comment]
I appreciate the feedback, and while it's a neat idea I'm not really interested in putting the work in to develop it. If you (or anyone else) wants to submit a PR, I'd be happy to consider it. I'll leave this open for a while in case anyone else sees this and feels like submitting a PR.

Sorry.
