### ISSUE TITLE
DOM Not Working

### ISSUE THREAD

**Issue by LoopForYou** [ChrisMuir/Zillow#7]
Hello,

It seems the class for DOM has changed to (if input into console)
`document.getElementsByClassName('zsg-list_inline zsg-photo-card-badge');`

I tried updating this myself, but don't have enough python knowledge to do that. Can you fix it?

**Comment by LoopForYou** [comment]
Also, this is cool for learning and utility. Throw some donation crypto addresses on the readme so I can pay in Stellars, Bitcoin, Etherium, KIN, Doge.... etc...

**Comment by ChrisMuir** [comment]
Thanks for the heads up on this, pushed a bug fix via commit [70ca547](https://github.com/ChrisMuir/Zillow/commit/70ca5477e1d25b84f2406273bf267cc1b0730e9c).

Also, I'm glad you've found the repo useful, thank you for the kind words! I'm not interested in collecting money for this work.

Thanks again!
